In [12]:
import tensorflow as tf, Variable, ones
from IPython import display

## A Simple Dense Layer
Dense layer = one of the hidden layers in a neural network

This notebook demonstrates creating a single dense layer
![img](./simpleANN.png)

# Building dense layer with the low level apis

In [52]:
# Defining borrow_features as features to predict if someone will apply for credit crad. Here there is only one example.
borrower_features = tf.constant([[ 2,  2, 43]], tf.float32)

bias1 = Variable(1.0)
weights1 = Variable(tf.ones((3, 2)))
print("borrower_features", borrower_features)
product1 = matmul(borrower_features, weights1)
print("product1", product1.numpy())
dense1 = keras.activations.sigmoid(product1 + bias1)
print("dense1:", dense1.numpy())

# Initialize bias2 and weights2
bias2 = Variable(1.0)
weights2 = Variable(ones((2, 1)))

# Perform matrix multiplication of dense1 and weights2
product2 = matmul(dense1, weights2)

# Apply activation to product2 + bias2 and print the prediction
prediction = keras.activations.sigmoid(product2 + bias2)
print('\n prediction: {}'.format(prediction.numpy()[0,0]))
print('\n actual: 1')

# Take note that this is only a forward propagation. No back-propagation is involved yet


borrower_features tf.Tensor([[ 2.  2. 43.]], shape=(1, 3), dtype=float32)
product1 [[47. 47.]]
dense1: [[1. 1.]]

 prediction: 0.9525741338729858

 actual: 1


In [60]:
# Assuming now there are 5 examples provided
# and 3 features are still used for the prediction

borrower_features = tf.Variable([
        [ 3.,  3., 23.],
        [ 2.,  1., 24.],
        [ 1.,  1., 49.],
        [ 1.,  1., 49.],
        [ 2.,  1., 29.]
    ], tf.float32)

bias1 = Variable(1.0)
weights1 = Variable(tf.ones((3, 2)))
products1 = matmul(borrower_features, weights1)
dense1 = keras.activations.sigmoid(products1 + bias1)

bias2 = Variable(1.0)
weights2 = Variable(ones((2, 1)))
products2 = matmul(dense1, weights2)
dense2 = keras.activations.sigmoid(products2 + bias2)

print(dense2) # Output should contain 5 predictions

tf.Tensor(
[[0.95257413]
 [0.95257413]
 [0.95257413]
 [0.95257413]
 [0.95257413]], shape=(5, 1), dtype=float32)


In [57]:
# Define inputs (features), weights and bias
inputs = tf.constant([[1, 35]], tf.float32)
weights = tf.Variable([[-0.05], [-0.01]])
bias = tf.Variable([0.5], tf.float32) # This plays the similar role as an intercept in a regression model

# To manually create a simple dense layer (Of a single perceptron in this case)

# We first we multiply inputs (features) by the weights
product = tf.matmul(inputs, weights) #; print(product.numpy())

# Manually define a single dense layer
denseManual = tf.keras.activations.sigmoid(product + bias)
print(denseManual)

tf.Tensor([[0.5249792]], shape=(1, 1), dtype=float32)


### Using Tensorflow's high level api to create a dense layer

In [20]:
inputs = tf.constant([[1, 35]], tf.float32)

denseTFLayer1 = tf.keras.layers.Dense(units=10, activation='sigmoid')(inputs) # 10 outgoing nodes, with sigmoid activation function
print(denseTFLayer1)

tf.Tensor(
[[2.4548173e-04 1.0000000e+00 9.9889177e-01 1.0000000e+00 2.1472573e-04
  9.8511577e-01 1.9801770e-10 9.1243708e-01 3.9992587e-10 8.6853108e-10]], shape=(1, 10), dtype=float32)


In [21]:
denseTFLayer2 = tf.keras.layers.Dense(units=5, activation='sigmoid')(denseTFLayer1)
output = tf.keras.layers.Dense(units=1, activation='sigmoid')(denseTFLayer2)

In [22]:
print(output)

tf.Tensor([[0.48040682]], shape=(1, 1), dtype=float32)
