## A Simple Dense Layer
Dense layer = one of the hidden layers in a neural network

In [5]:
import tensorflow as tf

### Using the low level apis of Tensorflow to manually create a dense layer

In [6]:
# Define inputs (features), weights and bias
inputs = tf.constant([[1, 35]], tf.float32)
weights = tf.Variable([[-0.05], [-0.01]])
bias = tf.Variable([0.5]) # This plays the similar role as an intercept in a regression model

# To manually create a simple dense layer (Of a single perceptron in this case)

# We first we multiply inputs (features) by the weights
product = tf.matmul(inputs, weights) #; print(product.numpy())

# Manually define a single dense layer
denseManual = tf.keras.activations.sigmoid(product + bias)
print(denseManual)

tf.Tensor([[0.5249792]], shape=(1, 1), dtype=float32)


### Using Tensorflow's high level api to create a dense layer

In [7]:
inputs = tf.constant([[1, 35]], tf.float32)

denseTFLayer1 = tf.keras.layers.Dense(units=10, activation='sigmoid')(inputs) # 10 outgoing nodes, with sigmoid activation function
print(denseTFLayer1)

tf.Tensor(
[[9.9881095e-01 1.8778170e-11 1.0000000e+00 3.7565529e-03 1.8374446e-01
  1.0000000e+00 1.0000000e+00 9.5690469e-11 1.0000000e+00 8.7170690e-02]], shape=(1, 10), dtype=float32)


In [8]:
denseTFLayer2 = tf.keras.layers.Dense(units=5, activation='sigmoid')(denseTFLayer1)
output = tf.keras.layers.Dense(units=1, activation='sigmoid')(denseTFLayer2)

In [9]:
print(output)

tf.Tensor([[0.3814729]], shape=(1, 1), dtype=float32)
