In [16]:
import tensorflow as tf
# One can check tensorflow's version with print(tf.version)

In [17]:
# 0D Tensor (Literally a scalar value)
d0 = tf.ones((1,))
print("Rank-0 Tensor:", d0.numpy())

# 1D Tensor (Aka. Vector)
d1 = tf.ones((2,))
print("Rank-1 Tensor:", d1.numpy())

#3D Tensor
d3 = tf.ones((2,2,2))
print("Rank-3 Tensor", d3.numpy())

Rank-0 Tensor: [1.]
Rank-1 Tensor: [1. 1.]
Rank-3 Tensor [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


A constant is the simplest category of a Tensor
* Not trainable 
* Can have any dimension

In [18]:
from tensorflow import constant

# To define a 2x3 constant
a = constant(3, shape=[2,3])
print(a.numpy())

# To define a 2x2 constant
b = tf.constant([1,2,3,4], shape=[2,2])
print("A Rank-2 Tensor as a constant:", b.numpy())

[[3 3 3]
 [3 3 3]]
A Rank-2 Tensor as a constant: [[1 2]
 [3 4]]


In [19]:
# Multiplication
from tensorflow import ones, matmul, multiply

#Defining Tensors
A0  = ones(1)#; print(A0.numpy())
A31 = ones([3,1])#; print(A31)
A31_twos_col = constant(2, dtype=1, shape=[3,1])#; print(A31_twos) 
A31_twos_row = constant(2, dtype=1, shape=[1,3])#; print(A31_twos) 


print(multiply(A31, A31_twos_col).numpy())
print(matmul(A31, A31_twos_row).numpy())

[[2.]
 [2.]
 [2.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [20]:
# Reduce sum
from tensorflow import reduce_sum

# Defining a 2D matrix
A = tf.Variable([[1,2], [3,4]], shape=(2,2))
print(A.numpy())
print(reduce_sum(A, 0)) # [1,2] + [3,4] = [4, 6]
print(reduce_sum(A, 1)) # [1,3] + [2,4] = [3, 7]

# Defining a 2x3x4 tensor of ones
A = ones([2,3,4])
print(A.numpy())

print("Reducing on all dimensions: ", reduce_sum(A).numpy())
reduceOnRows = reduce_sum(A, 0) 
print("Reducing on dimension 0 (rows):", reduceOnRows.numpy(), reduceOnRows.numpy().shape) # [1,1,1] + [1,1,1] + [1,1,1]

[[1 2]
 [3 4]]
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([3 7], shape=(2,), dtype=int32)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Reducing on all dimensions:  24.0
Reducing on dimension 0 (rows): [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]] (3, 4)


In [28]:
# Importing external data with Tensorflow
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
train_file_path = tf.keras.utils.get_file("train.csv", TRAIN_DATA_URL)

print(type(train_file_path))

<class 'str'>
